/*
 * GPIO_interface.h
 *
 *  Created on: Feb 3, 2021
 *      Author: mohab
 */

#ifndef GPIO_INTERFACE_H_
#define GPIO_INTERFACE_H_

/* GPIO PORT ENUM */
typedef enum{
	GPIO_ENUM_PORTA=0,
	GPIO_ENUM_PORTB,
	GPIO_ENUM_PORTC,
	GPIO_ENUM_TOTAL_PORTS
}GPIO_EnumPort_type;

/* GPIO PINS ENUM */
typedef enum{
	GPIO_ENUM_PIN0=0,
	GPIO_ENUM_PIN1,
	GPIO_ENUM_PIN2,
	GPIO_ENUM_PIN3,
	GPIO_ENUM_PIN4,
	GPIO_ENUM_PIN5,
	GPIO_ENUM_PIN6,
	GPIO_ENUM_PIN7,
	GPIO_ENUM_PIN8,
	GPIO_ENUM_PIN9,
	GPIO_ENUM_PIN10,
	GPIO_ENUM_PIN11,
	GPIO_ENUM_PIN12,
	GPIO_ENUM_PIN13,
	GPIO_ENUM_PIN14,
	GPIO_ENUM_PIN15,
	GPIO_ENUM_TOTAL_PINS
}GPIO_EnumPin_type;

/* GPIO PINs Modes ENUM */
typedef enum{
	/* GPIO INPUT options */
	GPIO_ENUM_INPUT_ANALOG =0b0000,
	GPIO_ENUM_INPUT_FLOATING=0b0100,
	GPIO_ENUM_INPUT_PULL_UP_DOWN=0b1000,

	/* GPIO OUTPUT 2 MHz options */
	GPIO_ENUM_OUTPUT_2MHZ_PP=0b0010,
	GPIO_ENUM_OUTPUT_2MHZ_OD=0b0110,
	GPIO_ENUM_OUTPUT_2MHZ_AF_PP=0b1010,
	GPIO_ENUM_OUTPUT_2MHZ_AF_OD=0b1110,

	/* GPIO OUTPUT 10 MHz options */
	GPIO_ENUM_OUTPUT_10MHZ_PP=0b0001,
	GPIO_ENUM_OUTPUT_10MHZ_OD=0b0101,
	GPIO_ENUM_OUTPUT_10MHZ_AF_PP=0b1001,
	GPIO_ENUM_OUTPUT_10MHZ_AF_OD=0b1101,

	/* GPIO OUTPUT 50 MHz options */
	GPIO_ENUM_OUTPUT_50MHZ_PP=0b0011,
	GPIO_ENUM_OUTPUT_50MHZ_OD=0b0111,
	GPIO_ENUM_OUTPUT_50MHZ_AF_PP=0b1011,
	GPIO_ENUM_OUTPUT_50MHZ_AF_OD=0b1111
}GPIO_EnumPinMode_type;

/* GPIO PIN value ENUM */
typedef enum{
	GPIO_ENUM_HIGH=1,
	GPIO_ENUM_LOW=0
}GPIO_EnumPinValue_type;

void GPIO_voidSetPinDirection(GPIO_EnumPort_type Copy_EnumPortID, GPIO_EnumPin_type Copy_EnumPinID, GPIO_EnumPinMode_type Copy_EnumMode);
void GPIO_voidSetPinValue(GPIO_EnumPort_type Copy_EnumPortID, GPIO_EnumPin_type Copy_EnumPinID, GPIO_EnumPinMode_type Copy_EnumValue);
u8 GPIO_u8GetPinValue(GPIO_EnumPort_type Copy_EnumPortID, GPIO_EnumPin_type Copy_EnumPinID);

/* SET PORT DIRECTION */
void GPIO_voidSetPortDirection(GPIO_EnumPort_type Copy_EnumPortID, GPIO_EnumPinMode_type Copy_EnumMode);
/* SET PORT VALUE */
void GPIO_voidSetPortValue(GPIO_EnumPort_type Copy_EnumPortID, GPIO_EnumPinMode_type Copy_EnumValue);

#endif /* GPIO_INTERFACE_H_ */
