/*
 * NVIC_interface.h
 *
 *  Created on: Feb 7, 2021
 *      Author: mohab
 */

#ifndef NVIC_INTERFACE_H_
#define NVIC_INTERFACE_H_

/* NVIC peripherals Positions*/
typedef enum{
	NVIC_ENUM_WWDG=0,
	NVIC_ENUM_PVD,
	NVIC_ENUM_TAMPER,
	NVIC_ENUM_RTC,
	NVIC_ENUM_FLASH,
	NVIC_ENUM_RCC,
	NVIC_ENUM_EXTI0,
	NVIC_ENUM_EXTI1,
	NVIC_ENUM_EXTI2,
	NVIC_ENUM_EXTI3,
	NVIC_ENUM_EXTI4,
	NVIC_ENUM_DMA1_Channel1,
	NVIC_ENUM_DMA1_Channel2,
	NVIC_ENUM_DMA1_Channel3,
	NVIC_ENUM_DMA1_Channel4,
	NVIC_ENUM_DMA1_Channel5,
	NVIC_ENUM_DMA1_Channel6,
	NVIC_ENUM_DMA1_Channel7,
	NVIC_ENUM_ADC1_2,
	NVIC_ENUM_USB_HP_CAN_TX,
	NVIC_ENUM_USB_LP_CAN_RX0,
	NVIC_ENUM_CAN_RX1,
	NVIC_ENUM_CAN_SCE,
	NVIC_ENUM_EXTI9_5,
	NVIC_ENUM_TIM1_BRK,
	NVIC_ENUM_TIM1_UP,
	NVIC_ENUM_TIM1_TRG_COM,
	NVIC_ENUM_TIM1_CC,
	NVIC_ENUM_TIM2,
	NVIC_ENUM_TIM3,
	NVIC_ENUM_TIM4,
	NVIC_ENUM_I2C1_EV,
	NVIC_ENUM_I2C1_ER,
	NVIC_ENUM_I2C2_EV,
	NVIC_ENUM_I2C2_ER,
	NVIC_ENUM_SPI1,
	NVIC_ENUM_SPI2,
	NVIC_ENUM_USART1,
	NVIC_ENUM_USART2,
	NVIC_ENUM_USART3,
	NVIC_ENUM_EXTI15_10,
	NVIC_ENUM_RTCAlarm,
	NVIC_ENUM_USBWakeup,
	NVIC_ENUM_TIM8_BRK,
	NVIC_ENUM_TIM8_UP,
	NVIC_ENUM_TIM8_TRG_COM,
	NVIC_ENUM_TIM8_CC,
	NVIC_ENUM_ADC3,
	NVIC_ENUM_FSMC,
	NVIC_ENUM_SDIO,
	NVIC_ENUM_TIM5,
	NVIC_ENUM_SPI3,
	NVIC_ENUM_UART4,
	NVIC_ENUM_UART5,
	NVIC_ENUM_TIM6,
	NVIC_ENUM_TIM7,
	NVIC_ENUM_DMA2_Channel1,
	NVIC_ENUM_DMA2_Channel2,
	NVIC_ENUM_DMA2_Channel3,
	NVIC_ENUM_DMA2_Channel4_5,
	NVIC_ENUM_TOTAL_PERIPHERALS
}NVIC_EnumPeripheralPosition_type;

typedef enum{
	NVIC_ENUM_GROUP0=0,
	NVIC_ENUM_GROUP1,
	NVIC_ENUM_GROUP2,
	NVIC_ENUM_GROUP3,
	NVIC_ENUM_GROUP4,
	NVIC_ENUM_GROUP5,
	NVIC_ENUM_GROUP6,
	NVIC_ENUM_GROUP7,
	NVIC_ENUM_GROUP8,
	NVIC_ENUM_GROUP9,
	NVIC_ENUM_GROUP10,
	NVIC_ENUM_GROUP11,
	NVIC_ENUM_GROUP12,
	NVIC_ENUM_GROUP13,
	NVIC_ENUM_GROUP14,
	NVIC_ENUM_GROUP15,
	NVIC_ENUM_TOTAL_GROUPS
}NVIC_EnumPriorityGroupNum_type;

typedef enum{
	NVIC_ENUM_SUB0=0,
	NVIC_ENUM_SUB1,
	NVIC_ENUM_SUB2,
	NVIC_ENUM_SUB3,
	NVIC_ENUM_SUB4,
	NVIC_ENUM_SUB5,
	NVIC_ENUM_SUB6,
	NVIC_ENUM_SUB7,
	NVIC_ENUM_SUB8,
	NVIC_ENUM_SUB9,
	NVIC_ENUM_SUB10,
	NVIC_ENUM_SUB11,
	NVIC_ENUM_SUB12,
	NVIC_ENUM_SUB13,
	NVIC_ENUM_SUB14,
	NVIC_ENUM_SUB15,
	NVIC_ENUM_TOTAL_SUBS
}NVIC_EnumPrioritySubNum_type;


/* NVIC Functions */
void NVIC_voidInit(void);

void NVIC_voidEnableInterrupt(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum);

void NVIC_voidDisableInterrupt(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum);

void NVIC_voidSetPendingFlag(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum);

void NVIC_voidClearPendingFlag(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum);

u8	 NVIC_u8GetActiveFlag(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum);

void NVIC_voidSetPriority(NVIC_EnumPeripheralPosition_type Copy_EnumInterruptNum , NVIC_EnumPriorityGroupNum_type Copy_EnumGroupPriority, NVIC_EnumPrioritySubNum_type Copy_EnumGSubPriority);

#endif /* NVIC_INTERFACE_H_ */
