/*
 * EXTI_config.h
 *
 *  Created on: Feb 8, 2021
 *      Author: mohab
 */

#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_

/* Choose from :
		EXTI_RISING
		EXTI_FALLING
		EXTI_ANY_LOGIC_CHANGE */

#define EXTI_LINE0_EDGE 				EXTI_FALLING
#define EXTI_LINE1_EDGE 				EXTI_FALLING
#define EXTI_LINE2_EDGE 				EXTI_FALLING
#define EXTI_LINE3_EDGE 				EXTI_FALLING
#define EXTI_LINE4_EDGE 				EXTI_FALLING
#define EXTI_LINE5_EDGE 				EXTI_FALLING
#define EXTI_LINE6_EDGE 				EXTI_FALLING
#define EXTI_LINE7_EDGE 				EXTI_FALLING
#define EXTI_LINE8_EDGE 				EXTI_FALLING
#define EXTI_LINE9_EDGE 				EXTI_FALLING
#define EXTI_LINE10_EDGE 				EXTI_FALLING
#define EXTI_LINE11_EDGE 				EXTI_FALLING
#define EXTI_LINE12_EDGE				EXTI_FALLING
#define EXTI_LINE13_EDGE				EXTI_FALLING
#define EXTI_LINE14_EDGE 				EXTI_FALLING
#define EXTI_LINE15_EDGE 				EXTI_FALLING



#endif /* EXTI_CONFIG_H_ */
